language: ruby
rvm:
  - 2.0.0
env:
  - DB=sqlite
script: 
  - RAILS_ENV=test bundle exec rake db:migrate --trace
before_script:
  - mysql -e 'create database my_app_test'
bundler_args: --binstubs=./bundler_stubs